Numpy is the fundamental package for numeric computing with Python. It provides powerful ways to create store and manipulate data, which makes it able to seamlessly and speedily integrate with a wide variety of databases and data formats. This is also the foundation that Pandas is built on which is a high performance data-centric package that we're going to learn more about in this course. 

In this lecture, we're going to talk about creating arrays with certain data types, manipulating arrays ,selecting elements from arrays and loading data sets into arrays. Such functions are useful for manipulating data and understanding the functionalities of other common python data packages

In [1]:
import numpy as np
import math

### Array Creation

In [5]:
a = np.array([1,2,3])
print(a)

# We can print the number of dimensions of a list using the ndim attribute
print(a.ndim)

[1 2 3]
1


In [7]:
# If we pass in a list of lists in numpy array, we create a multi-dimensional array, for instance, a matix
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# We can print out the length of each dimnesion by calling the shape attribute (return a tuple)
b.shape

(2, 3)

In [10]:
# We can also check the type of items in the array
a.dtype

dtype('int32')

In [11]:
# Besides integers, floats are also accepted in numpy arrays
c = np.array([2.2,5,1.1])
c.dtype.name

'float64'

In [12]:
c

array([2.2, 5. , 1.1])

In [14]:
# Sometimes we know the shape of array that we want to create, but not sure what to be in it.
# Numpy offers several functions to create arrays with initial placeholders, such as zero;s or one's

d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# We can also generate an array with random numbers

np.random.rand(2,3)

array([[0.26904508, 0.53195099, 0.62811633],
       [0.28970976, 0.53427158, 0.38971614]])

In [19]:
# We can also create a sequence of numbers in array with the arange() function.
# The first argument is the starting bound
# The second argument is the ending bound (not inclusive)
# The third argument is the difference between each consecutive numbers (spacing)

f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [21]:
# If we to generate a sequence of floats, we can use the linspace() function. 
# The third argument here is the total number of elements we want to generate

np.linspace(0,3,12)

array([0.        , 0.27272727, 0.54545455, 0.81818182, 1.09090909,
       1.36363636, 1.63636364, 1.90909091, 2.18181818, 2.45454545,
       2.72727273, 3.        ])

### Array Operations

In [22]:
# Arithmetic operators on array applay elementwise

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

c = a -b 
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [23]:
# Let's create an array of typical Ann arbor winter farenheit values
farenheit = np.array([0,-10,-5,-15,0])

celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [25]:
# Boolean array 
# We can apply an operator on an array, and a boolean array will be returned for any element in the original, with True being the output if it meets the condition.

celcius > -20

array([ True, False, False, False,  True])