In [1]:
import re

In [2]:
text = 'This is a good day.'

if re.search("good",text):
    print("wonderful!")
else:
    print("Not here!")

wonderful!


### 2. Tokenising

Tokenising is a core activity in natural language processing, where the string is separated into substrings based on patterns.

In [5]:
text = "Amy works diligently. Amy gets good grades and Amy is successful!"

re.split("Amy",text)

['', ' works diligently. ', ' gets good grades and ', ' is successful!']

In [6]:
re.findall("Amy",text)

['Amy', 'Amy', 'Amy']

The caret (^) character before string means that the text that the regex processor retrieves must start with it  
The dollar ($) character after the string meants that the text that the regex processor retrieves must start with it

In [8]:
re.search("^Amy",text)

<re.Match object; span=(0, 3), match='Amy'>

Note that the re.search() actually returned to us a re.Match object, which has a boolean value of True.

### 3. Patterns and Character classes

In [13]:
# Let's talk more about patterns and start with character classes. Let's create a string of a single learners
# Grades over a semester in one course across all of their assignments
grades = "ACAAABCBCBAAA"

re.findall("B",grades)

['B', 'B', 'B']

['A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A', 'A']

#### 3.1. Set operator

To list a set of letters/strings that we are trying to find in the text

In [15]:
# If we wanted to count the number of A's or B's in the list, we can't use "AB" since this is used to match all A's followed immediately by a B. 
# Instead to do so, we can do this

re.findall("[AB]",grades)

['A', 'A', 'A', 'A', 'B', 'B', 'B', 'A', 'A', 'A']

In [18]:
# To find a range of characters, we can also use hyphen "-" to set the range from A-Z or 1-9
re.findall("[A][B-C]",grades)

['AC', 'AB']

In [16]:
re.findall("AB|BC",grades)

['AB', 'BC']

In [19]:
# To find the opposite of our result, we can parse out only the grades which were not A'set
re.findall("[^A]",grades)

['C', 'B', 'C', 'B', 'C', 'B']

In [21]:
# It's an empty list, beacuse the regex says that we want to match any value at the beginning of the string which is not an A.
# Our string thought starts with an A, so there is no match found. 
# For set operator, we are doing character-based matching. So you are matching individuals characters in an OR method

re.findall("^[^A]",grades)

[]

In [28]:
web = "asddgbfg.casdwww..abc.comasfdbfghnfgh"

re.match(r"(\w.*)(.com)",web)

<re.Match object; span=(0, 25), match='asddgbfg.casdwww..abc.com'>

In [43]:
import numpy as np
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [69]:
a6 = np.arange(0,36,1)


b = a6.reshape(6,6)
b
b[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [73]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
result



['A', 'AA', 'AA', 'AA', 'A']

In [77]:

old = np.array([[1, 0, 1], [1, 3, 1]])

new = old
new[0, :2] = 0

array([[1, 0, 1],
       [1, 3, 1]])

In [75]:
new

array([[0, 0, 1],
       [1, 1, 1]])

In [80]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''


pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4
